import type {
  LoanApplication,
  ExpenditureItem,
  ExpenseClaim,
  PaymentEntry,
  BusinessTrainingCourse,
  User,
  Financier,
  SystemSettings,
  SystemHealth,
} from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    email: "john.client@example.com",
    name: "John Doe",
    role: "client",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    email: "sarah.financier@example.com",
    name: "Sarah Wilson",
    role: "financier",
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "3",
    email: "admin@loanplatform.com",
    name: "Admin User",
    role: "admin",
    createdAt: new Date("2024-01-01"),
  },
]

export const mockLoanApplications: LoanApplication[] = [
  {
    id: "loan-001",
    clientId: "1",
    clientName: "John Doe",
    kycNumber: "KYC123456789",
    amount: 50000,
    purpose: "Business expansion",
    status: "under-review",
    stage: "review",
    interestRate: 8.5,
    term: 24,
    documents: [
      {
        id: "doc-001",
        name: "Business Plan.pdf",
        type: "business-plan",
        url: "/documents/business-plan.pdf",
        status: "approved",
        uploadedAt: new Date("2024-01-20"),
        reviewedAt: new Date("2024-01-22"),
        reviewedBy: "Sarah Wilson",
      },
      {
        id: "doc-002",
        name: "Financial Projections.xlsx",
        type: "financial-projections",
        url: "/documents/financial-projections.xlsx",
        status: "pending",
        uploadedAt: new Date("2024-01-21"),
      },
    ],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-22"),
    reviewedBy: "Sarah Wilson",
  },
  {
    id: "loan-002",
    clientId: "1",
    clientName: "John Doe",
    kycNumber: "KYC123456789",
    amount: 25000,
    purpose: "Equipment purchase",
    status: "approved",
    stage: "disbursement",
    interestRate: 7.5,
    term: 18,
    documents: [],
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-25"),
    approvedBy: ["Sarah Wilson", "Mike Johnson"],
  },
]

export const mockExpenditureItems: ExpenditureItem[] = [
  {
    id: "exp-001",
    loanId: "loan-002",
    lineItem: "Office Equipment",
    allocatedAmount: 10000,
    spentAmount: 3500,
    remainingAmount: 6500,
    status: "available",
    claims: [],
  },
  {
    id: "exp-002",
    loanId: "loan-002",
    lineItem: "Marketing & Advertising",
    allocatedAmount: 5000,
    spentAmount: 2000,
    remainingAmount: 3000,
    status: "available",
    claims: [],
  },
  {
    id: "exp-003",
    loanId: "loan-002",
    lineItem: "Staff Training",
    allocatedAmount: 3000,
    spentAmount: 0,
    remainingAmount: 3000,
    status: "available",
    claims: [],
  },
]

export const mockExpenseClaims: ExpenseClaim[] = [
  {
    id: "claim-001",
    expenditureItemId: "exp-001",
    amount: 1500,
    description: "Purchase of office chairs and desks",
    type: "bank-transfer",
    documents: [
      {
        id: "doc-003",
        name: "Invoice-001.pdf",
        type: "other",
        url: "/documents/invoice-001.pdf",
        status: "pending",
        uploadedAt: new Date("2024-01-25"),
      },
    ],
    status: "pending",
    submittedAt: new Date("2024-01-25"),
  },
]

export const mockPaymentEntries: PaymentEntry[] = [
  {
    id: "pay-001",
    loanId: "loan-002",
    amount: 25000,
    referenceNumber: "REF123456789",
    status: "confirmed",
    paymentDate: new Date("2024-01-26"),
    confirmedAt: new Date("2024-01-26"),
    confirmedBy: "Admin User",
  },
  {
    id: "pay-002",
    loanId: "loan-001",
    amount: 50000,
    referenceNumber: "REF987654321",
    status: "pending",
    paymentDate: new Date("2024-01-27"),
  },
]

export const mockBusinessTrainingCourses: BusinessTrainingCourse[] = [
  {
    id: "course-001",
    title: "Financial Management for Small Business",
    provider: "Business Academy",
    duration: "4 weeks",
    description: "Learn essential financial management skills for running a successful business.",
    category: "Finance",
  },
  {
    id: "course-002",
    title: "Digital Marketing Fundamentals",
    provider: "Marketing Institute",
    duration: "6 weeks",
    description: "Master the basics of digital marketing to grow your business online.",
    category: "Marketing",
  },
  {
    id: "course-003",
    title: "Leadership and Team Management",
    provider: "Leadership Center",
    duration: "3 weeks",
    description: "Develop leadership skills to effectively manage and motivate your team.",
    category: "Management",
  },
]

export const mockFinanciers: Financier[] = [
  {
    id: "fin-001",
    name: "Capital Growth Partners",
    email: "contact@capitalgrowth.com",
    contactPerson: "Sarah Wilson",
    phone: "+1-555-0123",
    address: "123 Financial District, New York, NY 10004",
    registrationNumber: "FIN-REG-001",
    status: "active",
    loanLimit: 1000000,
    interestRateRange: {
      min: 6.5,
      max: 12.0,
    },
    specializations: ["SME Loans", "Equipment Financing", "Working Capital"],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "fin-002",
    name: "Business Development Fund",
    email: "info@bdfund.com",
    contactPerson: "Mike Johnson",
    phone: "+1-555-0456",
    address: "456 Commerce Street, Chicago, IL 60601",
    registrationNumber: "FIN-REG-002",
    status: "active",
    loanLimit: 500000,
    interestRateRange: {
      min: 7.0,
      max: 15.0,
    },
    specializations: ["Startup Funding", "Business Expansion", "Technology Loans"],
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "fin-003",
    name: "Regional Credit Union",
    email: "loans@regionalcu.org",
    contactPerson: "Emily Davis",
    phone: "+1-555-0789",
    address: "789 Main Street, Austin, TX 73301",
    registrationNumber: "FIN-REG-003",
    status: "suspended",
    loanLimit: 250000,
    interestRateRange: {
      min: 5.5,
      max: 10.0,
    },
    specializations: ["Personal Loans", "Small Business Loans"],
    createdAt: new Date("2023-12-15"),
    updatedAt: new Date("2024-01-25"),
  },
]

export const mockSystemSettings: SystemSettings[] = [
  {
    id: "set-001",
    category: "general",
    key: "platform_name",
    value: "Loan Management Platform",
    description: "The display name of the platform",
    type: "string",
    updatedAt: new Date("2024-01-01"),
    updatedBy: "Admin User",
  },
  {
    id: "set-002",
    category: "general",
    key: "max_loan_amount",
    value: "1000000",
    description: "Maximum loan amount allowed in the system",
    type: "number",
    updatedAt: new Date("2024-01-15"),
    updatedBy: "Admin User",
  },
  {
    id: "set-003",
    category: "security",
    key: "session_timeout",
    value: "3600",
    description: "Session timeout in seconds",
    type: "number",
    updatedAt: new Date("2024-01-10"),
    updatedBy: "Admin User",
  },
  {
    id: "set-004",
    category: "notifications",
    key: "email_notifications",
    value: "true",
    description: "Enable email notifications",
    type: "boolean",
    updatedAt: new Date("2024-01-20"),
    updatedBy: "Admin User",
  },
  {
    id: "set-005",
    category: "integrations",
    key: "payment_gateway_url",
    value: "https://api.paymentgateway.com",
    description: "Payment gateway API endpoint",
    type: "string",
    updatedAt: new Date("2024-01-25"),
    updatedBy: "Admin User",
  },
]

export const mockSystemHealth: SystemHealth[] = [
  {
    service: "Database",
    status: "healthy",
    lastCheck: new Date(),
    responseTime: 45,
  },
  {
    service: "Payment Gateway",
    status: "healthy",
    lastCheck: new Date(),
    responseTime: 120,
  },
  {
    service: "Email Service",
    status: "warning",
    lastCheck: new Date(),
    responseTime: 2500,
    errorMessage: "High response time detected",
  },
  {
    service: "Document Storage",
    status: "healthy",
    lastCheck: new Date(),
    responseTime: 80,
  },
  {
    service: "Authentication Service",
    status: "error",
    lastCheck: new Date(),
    errorMessage: "Connection timeout",
  },
]
